---
# Special playbook to install only SSL related details.

- name: SSL Phase 1 (Prepare Servers)
  hosts: all
  remote_user: larsgeorge
  become: yes

  roles:
    - { role: ssl-phase-1, when: SECURITY_ENABLED == true }

- name: SSL Phase 2 (Sign CSRs)
  hosts: kdc_server
  remote_user: larsgeorge
  become: yes

  roles:
    - { role: ssl-phase-2, when: SECURITY_ENABLED == true }

- name: SSL Phase 3 (Install CSRs and Truststores)
  hosts: all
  remote_user: larsgeorge
  become: yes

  roles:
    - { role: ssl-phase-3, when: SECURITY_ENABLED == true }

