---
# Purpose: Install HBase RegionServer
#
# Notes:
#   - Executed on all dedicated servers in the cluster

# Configure service script

- name: Template HBase RegionServer startup scripts
  template:
    src={{ item.src }}
    dest=/etc/systemd/system/{{ item.dest }}
    owner=root
    group=root
    mode=755
    backup=yes
  with_items:
    - { src: 'etc/systemd/system/hbase-regionserver.service.j2', dest: 'hbase-regionserver.service'}